//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SensorDataCommon.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataSource
    {
        public int Id { get; set; }
        public string DeviceId { get; set; }
        public Nullable<int> ChannelId { get; set; }
        public string Description { get; set; }
        public int DataTypeId { get; set; }
    
        public virtual DataType DataType { get; set; }
    }
}
